theme: jekyll-theme-slate
show_downloads: true
title: The TXT Hider
description: Hide Text in Images!
github:
  zip_url: https://github.com/SagarDevAchar/TheTXTHider/releases/download/release/The.TXT.Hider.v2022.07.19.zip
  tar_url: https://github.com/SagarDevAchar/TheTXTHider/archive/refs/tags/release.tar.gz
